version: "3.8"

services:
  postgres-test:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    container_name: galacash-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: galacash
      POSTGRES_PASSWORD: galacash123
      POSTGRES_DB: galacash_test_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galacash"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  redis-test:
    image: public.ecr.aws/docker/library/redis:7-alpine
    container_name: galacash-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
